# Generated by Django 4.0.5 on 2022-06-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('worker_login', models.CharField(max_length=255)),
                ('worker_password', models.CharField(max_length=255)),
                ('cashier', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('salary', models.IntegerField()),
                ('storehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='storehouse.storehouse')),
            ],
        ),
    ]
