# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from datetime import datetime
from decimal import Decimal


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1051, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.Worker = QtWidgets.QWidget()
        self.Worker.setObjectName("Worker")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 161, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 90, 161, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 140, 161, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 190, 161, 31))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(10, 240, 161, 31))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(10, 400, 161, 31))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(10, 290, 161, 31))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(10, 350, 161, 31))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.tableWidget = QtWidgets.QTableWidget(self.Worker)
        self.tableWidget.setGeometry(QtCore.QRect(180, 40, 851, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(10, 520, 161, 31))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.label = QtWidgets.QLabel(self.Worker)
        self.label.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Worker)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Worker)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Worker)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Worker)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Worker)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 67, 17))
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.Worker)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(10, 450, 161, 31))
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.label_7 = QtWidgets.QLabel(self.Worker)
        self.label_7.setGeometry(QtCore.QRect(10, 330, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Worker)
        self.label_8.setGeometry(QtCore.QRect(10, 380, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Worker)
        self.label_9.setGeometry(QtCore.QRect(10, 430, 111, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Worker)
        self.label_10.setGeometry(QtCore.QRect(10, 500, 67, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.Worker)
        self.pushButton.setGeometry(QtCore.QRect(190, 450, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Worker)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 450, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Worker)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 450, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Worker)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 520, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.Worker, "")
        self.Statistics = QtWidgets.QWidget()
        self.Statistics.setObjectName("Statistics")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.Statistics)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(30, 500, 131, 31))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.label_11 = QtWidgets.QLabel(self.Statistics)
        self.label_11.setGeometry(QtCore.QRect(30, 480, 67, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Statistics)
        self.label_12.setGeometry(QtCore.QRect(310, 500, 131, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Statistics)
        self.label_13.setGeometry(QtCore.QRect(440, 500, 67, 17))
        self.label_13.setObjectName("label_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.Statistics)
        self.pushButton_5.setGeometry(QtCore.QRect(178, 504, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Statistics)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 1051, 471))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        self.tabWidget.addTab(self.Statistics, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.load_prods()
        self.load_worker()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "full_name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "position"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "worker_login"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "worker_password"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "cashier"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "salary"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Storehouse_id"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Storehouse"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Position"))
        self.label_4.setText(_translate("MainWindow", "Login"))
        self.label_5.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "Cashier "))
        self.label_7.setText(_translate("MainWindow", "Manager"))
        self.label_8.setText(_translate("MainWindow", "Salary"))
        self.label_9.setText(_translate("MainWindow", "StoreHouse ID"))
        self.label_10.setText(_translate("MainWindow", "Search"))
        self.pushButton.setText(_translate("MainWindow", "ADD"))
        self.pushButton_2.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_3.setText(_translate("MainWindow", "DELETE"))
        self.pushButton_4.setText(_translate("MainWindow", "SEARCH"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Worker), _translate("MainWindow", "Worker"))
        self.label_11.setText(_translate("MainWindow", "Date"))
        self.label_12.setText(_translate("MainWindow", "Tax you must paid:"))
        self.label_13.setText(_translate("MainWindow", "0"))
        self.pushButton_5.setText(_translate("MainWindow", "CALCULATE"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phone "))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Order Created"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Order Updated"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Payed"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Order Key"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "StoreHouse"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Statistics), _translate("MainWindow", "Statistics"))
        self.pushButton_5.clicked.connect(self.tax_calculate)
        self.pushButton.clicked.connect(self.add_worker)
        self.pushButton_3.clicked.connect(self.delete_worker)
        self.pushButton_2.clicked.connect(self.update_worker)
        self.pushButton_4.clicked.connect(self.findbyname)

    def load_prods(self):
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        sql = "SELECT * FROM orders_orderitem INNER JOIN orders_order ON " \
              "orders_orderitem.order_id = orders_order.id " \
              "INNER JOIN store_product ON orders_orderitem.product_id =  store_product.id " \
              "INNER JOIN storehouse_storehouse ON orders_order.Storehouse_id = storehouse_storehouse.id"
        db_cursor.execute(sql)
        total = db_cursor.rowcount
        print("Total Data Entries:" + str(total))
        db = db_cursor.fetchall()
        rows = 0
        self.tableWidget_2.setRowCount(len(db))
        for item in db:
            if item[12] == 1:
                self.tableWidget_2.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(item[0])))
                self.tableWidget_2.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(item[6])))
                self.tableWidget_2.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(item[7])))
                self.tableWidget_2.setItem(rows, 3, QtWidgets.QTableWidgetItem(str(item[8])))
                self.tableWidget_2.setItem(rows, 4, QtWidgets.QTableWidgetItem(str(item[9])))
                self.tableWidget_2.setItem(rows, 5, QtWidgets.QTableWidgetItem(str(item[10])))
                self.tableWidget_2.setItem(rows, 6, QtWidgets.QTableWidgetItem(str(item[11])))
                self.tableWidget_2.setItem(rows, 7, QtWidgets.QTableWidgetItem(str(item[12])))
                self.tableWidget_2.setItem(rows, 8, QtWidgets.QTableWidgetItem(str(item[28])))
                self.tableWidget_2.setItem(rows, 9, QtWidgets.QTableWidgetItem(str(item[16])))
                rows += 1

    def load_worker(self):
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        sql = "SELECT * FROM worker_worker INNER JOIN storehouse_storehouse ON " \
              "worker_worker.storehouse_id = storehouse_storehouse.id "
        db_cursor.execute(sql)
        total = db_cursor.rowcount
        print("Total Data Entries:" + str(total))
        db = db_cursor.fetchall()
        rows = 0
        self.tableWidget.setRowCount(len(db))
        for item in db:
            self.tableWidget.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(item[0])))
            self.tableWidget.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(item[1])))
            self.tableWidget.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(item[2])))
            self.tableWidget.setItem(rows, 3, QtWidgets.QTableWidgetItem(str(item[3])))
            self.tableWidget.setItem(rows, 4, QtWidgets.QTableWidgetItem(str(item[4])))
            self.tableWidget.setItem(rows, 5, QtWidgets.QTableWidgetItem(str(item[5])))
            self.tableWidget.setItem(rows, 6, QtWidgets.QTableWidgetItem(str(item[6])))
            self.tableWidget.setItem(rows, 7, QtWidgets.QTableWidgetItem(str(item[8])))
            self.tableWidget.setItem(rows, 8, QtWidgets.QTableWidgetItem(str(item[10])))
            rows += 1

    def tax_calculate(self):
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        sql = "SELECT * FROM orders_orderitem INNER JOIN orders_order ON " \
              "orders_orderitem.order_id = orders_order.id " \
              "INNER JOIN store_product ON orders_orderitem.product_id =  store_product.id " \
              "INNER JOIN storehouse_storehouse ON orders_order.Storehouse_id = storehouse_storehouse.id"
        db_cursor.execute(sql)
        total = db_cursor.rowcount
        print("Total Data Entries:" + str(total))
        db = db_cursor.fetchall()
        date = self.plainTextEdit_6.toPlainText()
        date = datetime.strptime(date, '%Y.%m')
        suma = 0
        tax_procent = 0.22
        for item in db:
            if item[9].year == date.year:
                if item[9].month == date.month:
                    if item[12] == 1:
                        suma += item[10]
        tax = suma * Decimal(tax_procent)
        self.label_13.setText(str(tax))

    def add_worker(self):
        id = self.plainTextEdit.toPlainText()
        name = self.plainTextEdit_2.toPlainText()
        position = self.plainTextEdit_3.toPlainText()
        login = self.plainTextEdit_4.toPlainText()
        password = self.plainTextEdit_5.toPlainText()
        cashier = self.plainTextEdit_8.toPlainText()
        manager = self.plainTextEdit_9.toPlainText()
        salary = self.plainTextEdit_7.toPlainText()
        Storehouse_id = self.plainTextEdit_11.toPlainText()
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        query2 =f"INSERT INTO `storebd`.`worker_worker` (`full_name`, `position`, `worker_login`, `worker_password`, `cashier`, `manager`, `salary`, `storehouse_id`) VALUES ('{name}', '{position}', '{login}', '{password}', '{cashier}', '{manager}', '{salary}', '{Storehouse_id}');"

        # implement query Sentence
        db_cursor.execute(query2)
        print('Information', "NEW WORKER ADDED")
        # Submit to database for execution
        db_connection.commit()
        self.load_worker()

    def delete_worker(self):
        id = self.plainTextEdit.toPlainText()
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        query2 = f"DELETE FROM `storebd`.`worker_worker` WHERE(`id` = '{id}');"
        # implement query Sentence
        db_cursor.execute(query2)
        print('Information', "WORKER DELETED")
        # Submit to database for execution
        db_connection.commit()
        self.load_worker()

    def update_worker(self):
        id = self.plainTextEdit.toPlainText()
        name = self.plainTextEdit_2.toPlainText()
        position = self.plainTextEdit_3.toPlainText()
        login = self.plainTextEdit_4.toPlainText()
        password = self.plainTextEdit_5.toPlainText()
        cashier = self.plainTextEdit_8.toPlainText()
        manager = self.plainTextEdit_9.toPlainText()
        salary = self.plainTextEdit_7.toPlainText()
        Storehouse_id = self.plainTextEdit_11.toPlainText()
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        db_connection.connect()
        Update = f"UPDATE `storebd`.`worker_worker` SET `full_name` = '{name}', `position` = '{position}', `worker_login` = '{login}', `worker_password` = '{password}', `cashier` = '{cashier}', `manager` = '{manager}', `salary` = '{salary}', `storehouse_id` = '{Storehouse_id}' WHERE (`id` = '{id}');"
        db_cursor.execute(Update)
        db_connection.commit()
        print("UPDATE COMPLITED")
        self.load_worker()

    def findbyname(self):
        search = self.plainTextEdit_10.toPlainText()
        db_connection = mysql.connector.connect(
            host="127.0.0.1",
            database='storebd',
            user="root",
            password="TheLastBit2303Yurik!",
            auth_plugin='mysql_native_password')
        db_cursor = db_connection.cursor(buffered=True)
        if db_connection.is_connected() == False:
            db_connection.connect()
        sql = "SELECT * FROM worker_worker INNER JOIN storehouse_storehouse ON " \
              "worker_worker.storehouse_id = storehouse_storehouse.id where full_name='" + search + "'"
        db_cursor.execute(sql)
        total = db_cursor.rowcount
        print("Total Data Entries:" + str(total))
        db = db_cursor.fetchall()
        rows = 0
        self.tableWidget.setRowCount(len(db))
        for item in db:
            self.tableWidget.setItem(rows, 0, QtWidgets.QTableWidgetItem(str(item[0])))
            self.tableWidget.setItem(rows, 1, QtWidgets.QTableWidgetItem(str(item[1])))
            self.tableWidget.setItem(rows, 2, QtWidgets.QTableWidgetItem(str(item[2])))
            self.tableWidget.setItem(rows, 3, QtWidgets.QTableWidgetItem(str(item[3])))
            self.tableWidget.setItem(rows, 4, QtWidgets.QTableWidgetItem(str(item[4])))
            self.tableWidget.setItem(rows, 5, QtWidgets.QTableWidgetItem(str(item[5])))
            self.tableWidget.setItem(rows, 6, QtWidgets.QTableWidgetItem(str(item[6])))
            self.tableWidget.setItem(rows, 7, QtWidgets.QTableWidgetItem(str(item[8])))
            self.tableWidget.setItem(rows, 8, QtWidgets.QTableWidgetItem(str(item[10])))
            rows += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
